<a href="https://colab.research.google.com/github/grkenney/WinSPIRE-HLC-Python/blob/main/Notebooks/Keys/Day_2.2_Subsetting_and_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Subsetting Pandas DataFrames I

You now know how to read external datasets into `pandas`. Let's put those skills to use and explore our data set further.

First, we have to re-import the pandas package. Let's load it with the nickname `pd`.

In [1]:
# load pandas with the nickname pd
import pandas as pd

Now, let's reload our data from the previous lesson.

In [2]:
# load the csv
url = 'https://github.com/grkenney/WinSPIRE-HLC-Python/raw/refs/heads/main/data/sample_data_expression_06092026.csv'
df = pd.read_csv(url)

In [3]:
# print the first few rows of the data frame
df.head()

   sample_id  well  timepoint     MKI67      MTOR       BAX       IRF1
0     657317     1          0  1.004377  1.379025  0.799135   0.672194
1     657317     2          8  0.894172  1.345400  0.956142   0.756379
2     657317     3         16  0.679445  1.098444  1.209928  99.000000
3     657317     4         24  0.721341  1.063588  1.586136   0.643022
4     407401     5          0  1.091682  0.843497  0.354864   0.489234

What if we decided we didn't want to keep all of the data recorded in this dataset? To do that, we need to learn how to `subset` `DataFrames`. Subsetting means taking a dataset and pulling out a small portion of it that we're interested in.

First, we'll look at a single column (you can use `head` to keep the printed result short):

In [4]:
# subset one column, the column named 'well'
df["well"].head()

0    1
1    2
2    3
3    4
4    5
Name: well, dtype: int64

We use the square brackets [ ] after the name of the `DataFrame` to tell `pandas` that we want to look at one of the columns. We put the name of the column in quotes to tell `pandas` exactly which column we want to look at. Try subsetting the `timepoint` column:

In [5]:
# subset the timepoint column
df["timepoint"].head()

0     0
1     8
2    16
3    24
4     0
Name: timepoint, dtype: int64

`pandas` simply showed us the result of subsetting the column, but it didn't save the result anywhere. Try saving the `timepoint` column to a new variable, `time`:

In [6]:
# save the timepoint column to a variable time
time = df["timepoint"]

We can also pull out multiple columns at a time to create a new `DataFrame`. If we were only interested in the `well` and `timepoint`, we can subset them like this:

In [7]:
# subset the columns well and timepoint
df[["well", "timepoint"]]

     well  timepoint
0       1          0
1       2          8
2       3         16
3       4         24
4       5          0
..    ...        ...
115    26         24
116    27          0
117    28          8
118    29         16
119    30         24

[120 rows x 2 columns]

Does that look familiar? Instead of putting a single string between the square brackets, we put a whole list of strings -- you can tell it's a list by the second set of square brackets. You can also create the list of columns you're interested in and subset the dataframe in two separate steps. This code works exactly the same as what we just did above.

In [8]:
# create a list of columns with well and timepoint and store in variable columns
columns = ["well", "timepoint"]
# subset df by columns and show the first 5 rows
df[columns].head(10)

   well  timepoint
0     1          0
1     2          8
2     3         16
3     4         24
4     5          0
5     6          8
6     7         16
7     8         24
8     9          0
9    10          8

**Exercise**: subset the columns `sample_id`, `timepoint`, and `MTOR` and save the result to a variable called `df_subset`:

In [9]:
# subset three columns and save to a new variable
columns = ["sample_id", "timepoint", "MTOR"]
df_subset = df[columns]
# take a look at the beginning of the new DataFrame
df_subset.head()

   sample_id  timepoint      MTOR
0     657317          0  1.379025
1     657317          8  1.345400
2     657317         16  1.098444
3     657317         24  1.063588
4     407401          0  0.843497

Now we've learned how to subset columns. How do we subset rows? We use a `method` of `DataFrame` called `iloc`. When you see `iloc`, think "index location" -- because we want to get the location where the row is a certain index. Let's try it:

In [10]:
# subset the row with index 1 with iloc
df.iloc[1]

sample_id    657317.000000
well              2.000000
timepoint         8.000000
MKI67             0.894172
MTOR              1.345400
BAX               0.956142
IRF1              0.756379
Name: 1, dtype: float64

That showed us the row with an index of 1. Similarly to subsetting columns, we can also subset multiple rows:

In [11]:
# subset the first three rows using a list of indices
df.iloc[[0, 1, 2]]

   sample_id  well  timepoint     MKI67      MTOR       BAX       IRF1
0     657317     1          0  1.004377  1.379025  0.799135   0.672194
1     657317     2          8  0.894172  1.345400  0.956142   0.756379
2     657317     3         16  0.679445  1.098444  1.209928  99.000000

That gave us a smaller `DataFrame` where the rows have an index of 0, 1, or 2. We can do the same thing with slicing syntax:

In [12]:
# subset the first three rows with slicing
df.iloc[0:3]

   sample_id  well  timepoint     MKI67      MTOR       BAX       IRF1
0     657317     1          0  1.004377  1.379025  0.799135   0.672194
1     657317     2          8  0.894172  1.345400  0.956142   0.756379
2     657317     3         16  0.679445  1.098444  1.209928  99.000000

Notice that this does the same thing as calling `head` with a value of 3:

In [13]:
# use head to get the first 3 rows
df.head(3)

   sample_id  well  timepoint     MKI67      MTOR       BAX       IRF1
0     657317     1          0  1.004377  1.379025  0.799135   0.672194
1     657317     2          8  0.894172  1.345400  0.956142   0.756379
2     657317     3         16  0.679445  1.098444  1.209928  99.000000

What if we want to grab some rows in the middle of the `DataFrame`?
Try subsetting the 100th through 105th row.
Hint: Don't forget that counting starts at `0` in Python!

In [14]:
# subset the 100th row through the 105th row
df.iloc[99:105]

     sample_id  well  timepoint     MKI67      MTOR       BAX      IRF1
99      872920    10         24  0.822682  0.883806  1.290706  0.686805
100     611879    11          0       NaN  0.978368  0.319055  0.771887
101     611879    12          8  0.872014  0.645572  0.451553  1.209648
102     611879    13         16  0.563841  0.277332  0.828812  1.976239
103     611879    14         24  0.282538  0.208205  0.918079  2.375526
104     639327    15          0  0.966420  1.508504  0.733929  0.624033

Notice the value of MKI67 in the 100th row. We'll want to address that later.

Congrats on making it to the end of this lesson -- we learned a lot!

- How to use square brackets `[]` to subset columns.
- How to use `iloc` to subset rows.

# Subsetting Pandas DataFrames II

So far, you learned how to subset dataframes by entire rows or entire columns. Now we're going to learn how to do both at the same time!

First, let's recall how you would subset three columns, `sample_id`, `timepoint`, and `MTOR`. Let's save it to a variable called `subset1`.

In [15]:
# subset the colums and save it to subset1
columns = ["sample_id", "timepoint", "MTOR"]
subset1 = df[columns]
# print the head of subset1
subset1.head()

   sample_id  timepoint      MTOR
0     657317          0  1.379025
1     657317          8  1.345400
2     657317         16  1.098444
3     657317         24  1.063588
4     407401          0  0.843497

Now, how would you subset the 6th row through the 10th row from the `subset1` dataframe? Let's save it to a variable called `subset2`.

In [16]:
# subset the 6th row through the 10th row and save it to subset2
subset2 = subset1.iloc[5:10]
subset2

   sample_id  timepoint       MTOR
5     407401          8   0.744733
6     407401         16  10.000000
7     407401         24   0.601544
8     835249          0   1.558191
9     835249          8   1.203945

Now the `subset2` dataframe has just the rows 5 through 10 and three columns. We can even subset rows and columns in the same line of code, instead of doing it on multiple lines like we did above. Let's try combining both `iloc` and square brackets `[]` on one line:

In [17]:
# subset rows & columns at the same time and save in subset3
subset3 = df[columns].iloc[5:10]
subset3

   sample_id  timepoint       MTOR
5     407401          8   0.744733
6     407401         16  10.000000
7     407401         24   0.601544
8     835249          0   1.558191
9     835249          8   1.203945

What do you notice about `subset3`? How does it compare to `subset2`?

In [18]:
# compare subset2 and subset3
subset2 == subset3

   sample_id  timepoint  MTOR
5       True       True  True
6       True       True  True
7       True       True  True
8       True       True  True
9       True       True  True

Now you try! Subset rows 11 and 12 and columns `well` and `BAX` on one line of code:

In [19]:
# subset rows 11 and 12 and columns well and BAX
df[["well", "BAX"]].iloc[11:13]

    well       BAX
11    12  1.200724
12    13  0.654451

Sometimes we don't know exactly which row(s) we want to subset ahead of time. What if we want to subset rows that have a certain value in the `well` column? We don't want to scroll through hundreds of rows to find them. The good news is: we don't have to! Let's use the `method` called `query`.  Inside the parentheses of `query` we'll enclose a statement in quotes with the name of the column and an expression.

In [20]:
# query the data frame for rows where well is 3
df.query("well == 3")

    sample_id  well  timepoint     MKI67      MTOR       BAX       IRF1
2      657317     3         16  0.679445  1.098444  1.209928  99.000000
32     840149     3          0  0.997241  0.991594  0.659341   0.320130
62     273129     3         16  0.924905  1.085951  0.496133   0.715524
92     870332     3          0  1.114311  1.355870       NaN   0.743873

The above cell showed us all the rows where `well` is equal to `3`. 

**Exercise:** Try to subset the rows where the `timepoint` is `0` and save it to a variable, `time0`:

In [21]:
# subset rows for timepoint 0 and save it to a variable time0
time0 = df.query("timepoint == 0")
# take a look at the beginning
time0.head()

    sample_id  well  timepoint     MKI67      MTOR       BAX      IRF1
0      657317     1          0  1.004377  1.379025  0.799135  0.672194
4      407401     5          0  1.091682  0.843497  0.354864  0.489234
8      835249     9          0  0.927146  1.558191  0.573121  0.327879
12     490084    13          0  1.160876  1.341622  0.654451  0.714437
16     452567    17          0  1.161433  1.367411  0.624315  0.339684

Now lets do the same for timepoint 8 and save it to a variable, `time8`:

In [22]:
# subset rows for timepoint 8 and save it to a variable time8
time8 = df.query("timepoint == 8")
# look at the beginning
time8.head()

    sample_id  well  timepoint     MKI67      MTOR       BAX      IRF1
1      657317     2          8  0.894172  1.345400  0.956142  0.756379
5      407401     6          8  1.006165  0.744733  0.462132  0.437316
9      835249    10          8  0.884159  1.203945  0.742982  0.337709
13     490084    14          8  0.865659  1.092111  0.938300  0.984037
17     452567    18          8  0.985706  0.957909  0.966135  0.517752

**Exercise**: How would you determine the number of rows with timepoint 0 in this `DataFrame`? Think back to the last lesson when we used the `len` function.

In [23]:
# number of rows in time0
len(time0)

30

How about the number of rows in timepoint 8

In [24]:
# number of rows in time8
len(time8)

30

We can use `query` on multiple columns at a time. Let's try to subset the rows for well 1 and timepoint 0.

In [25]:
# subset the rows where well is 1 and timepoint is 0
df.query("well == 1 and timepoint == 0")

    sample_id  well  timepoint     MKI67      MTOR       BAX      IRF1
0      657317     1          0  1.004377  1.379025  0.799135  0.672194
60     273129     1          0  1.211209  1.367944  0.328713  0.736282

We used the keyword `and` to chain together two statements inside the `query` function. Both statements have to be true for a row to be included.

Besides checking whether values are equal using ==, we can also use greater than, less than, greater than or equal, etc. Try subsetting the rows where MTOR is greater than 1 and BAX is less than 0.:

In [26]:
# find the number of rows where MTOR > 1 and BAX < 0.5
df.query("MTOR > 1 and BAX < 0.5")

     sample_id  well  timepoint     MKI67      MTOR       BAX      IRF1
40      993751    11          0  1.258557  1.025086  0.355701  0.657793
48      336989    19          0  1.020099  1.247689  0.396069  0.376907
49      336989    20          8  0.963887  1.135080  0.480496  0.378075
60      273129     1          0  1.211209  1.367944  0.328713  0.736282
61      273129     2          8  1.087695  1.223411  0.380281  0.769875
62      273129     3         16  0.924905  1.085951  0.496133  0.715524
72      266888    13          0  0.952927  1.089689  0.342949       NaN
73      266888    14          8  0.868313  1.027831  0.345458  0.484647
112     199598    23          0  0.919562  1.044329  0.465255  0.603266

Instead of `and`, we can use the keyword `or` to represent a query where *one* of the two conditions must be fulfilled. Try subsetting where MTOR is greater than 2 or IRF1 is greater than 2.

In [27]:
# find the number of rows where MTOR > 2 or IRF1 > 2
df.query("MTOR > 2 or IRF1 > 2")

     sample_id  well  timepoint      MKI67       MTOR       BAX       IRF1
2       657317     3         16   0.679445   1.098444  1.209928  99.000000
6       407401     7         16   0.937125  10.000000  0.567334   0.486034
39      804190    10         24   0.283505   0.301948  1.524435   2.130784
47      403695    18         24   0.719340   0.967197  1.050942  99.000000
63      273129     4         24   0.879013  99.000000  0.614811   0.761473
77      769101    18          8   0.957378  99.000000  1.015190   0.888381
95      870332     6         24  99.000000   0.335727  1.589089   2.085914
103     611879    14         24   0.282538   0.208205  0.918079   2.375526

In this lesson, you learned:

- How to use `iloc` and square brackets `[]` at the same time.
- How to use `query` to find rows where the column has a certain value.

**Exercise:**
* Using column subsetting, find the maximum and minimum values for `MTOR` in our data and store in variables max_mtor and min_mtor.
* Use a single subsetting operation to subset the data frame to the rows where expression of any gene is 99
* Try using the method `isna` on our data frame to count how many missing values we have. (Note, to get the sum, you will need to use the `sum` method instead of the `sum` function we talked about earlier).

In [28]:
# print the max value of MTOR
max(df["MTOR"])
# print the min value of MTOR
min(df["MTOR"])

0.14431466

In [29]:
# subset to rows where expression of any gene is 99
df.query("MKI67 == 99 or MTOR == 99 or BAX == 99 or IRF1 == 99")

    sample_id  well  timepoint      MKI67       MTOR        BAX       IRF1
2      657317     3         16   0.679445   1.098444   1.209928  99.000000
43     993751    14         24  99.000000   0.969624   0.800381   0.622906
47     403695    18         24   0.719340   0.967197   1.050942  99.000000
59     318517    30         24   0.596477   0.749895  99.000000   0.296975
63     273129     4         24   0.879013  99.000000   0.614811   0.761473
77     769101    18          8   0.957378  99.000000   1.015190   0.888381
90     917531     1         16   0.578660   0.487757  99.000000   0.901054
95     870332     6         24  99.000000   0.335727   1.589089   2.085914

In [30]:
# use the isna method on our data frame to test for missing values
df.isna()

# count the total number of missing values in the data frame
df.isna().sum()

sample_id    0
well         0
timepoint    0
MKI67        6
MTOR         6
BAX          6
IRF1         6
dtype: int64